[package]
name = "alacrittab"
version = "0.1.0"
authors = ["Luc Street <lucis-fluxum@users.noreply.github.com>"]
edition = "2018"
publish = false

[dependencies]
gtk = { version = "0.9.2", default-features = false, features = ["v3_24"] }
gio = "*"
glib = "*"
